package:
  name: giropops-senhas
  version: 0.1
  description: Password Generator by LinuxTips
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - ./melange.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - gcc
      - musl-dev
      - python3
      - python3-dev
      - py3-pip
      - py3-virtualenv

pipeline:
  - name: Build Python application
    runs: |
      WEBAPPDIR="${{targets.destdir}}/usr/share/webapps/giropops"
      mkdir -p "${WEBAPPDIR}"

      echo "#!/usr/share/webapps/giropops/venv/bin/python3" > "${WEBAPPDIR}/app.py"
      cat app.py >> "${WEBAPPDIR}/app.py"
      chmod +x "${WEBAPPDIR}/app.py"

      cp -r templates static "${WEBAPPDIR}"

      virtualenv "${WEBAPPDIR}/venv"

      sh -c "source '${WEBAPPDIR}/venv/bin/activate' && pip install -r requirements.txt"
